name: unit testing

on:
  pull_request:
    branches: ['master', 'develop']

jobs:
  unit_test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment automatically
        run: npm ci

      - name: Build Test
        run: npm run build

      - name: Unit Test
        run: npm run test:unit -u

      - name: Lint
        run: npm run lint
